bool robot_ready
bool robot_error
bool touch
bool gas
bool reverse_inching
bool inching
bool arc
bool allow_nonzero_setpoints
uint16 current_raw
uint16 voltage_raw
uint16 v_offset_raw
---
bool success
string message
