positions:
- start
- clear1_top
- clear1_inside
- WIRE_FORWARD:0.75
- DO7:ON
- DO7:OFF
- clear1_top
- clear2_top
- clear2_inside
- DO6:2
- clear2_top
- clear3_top
- clear3_inside
- DO5:1
- clear3_top
- start
schema: torch_cleaner_sequence_v2
